version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nsv-landingpage-dev
    ports:
      - "9201:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - erpnsv_prod_erpnsv_prod_network

networks:
  erpnsv_prod_erpnsv_prod_network:
    external: true