server {
    listen 80;

    location /api/ {
        proxy_pass http://erpnsv_prod-frontend-1:8080/api/;
        proxy_set_header Host erpnsv_prod-frontend-1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_set_header Cookie "";
        proxy_set_header X-Frappe-CSRF-Token "fetch";
        proxy_hide_header Set-Cookie;
    }

    location /files/ {
        proxy_pass http://erpnsv_prod-frontend-1:8080/files/;
        proxy_set_header Host erpnsv_prod-frontend-1;
        proxy_hide_header Set-Cookie;
    }

    location /private/files/ {
        proxy_pass http://erpnsv_prod-frontend-1:8080/private/files/;
        proxy_set_header Host erpnsv_prod-frontend-1;
        proxy_hide_header Set-Cookie;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
