server {
    listen 80;

    location /api/ {
        proxy_pass http://172.17.0.1:3333/api/;
        proxy_set_header Host 172.17.0.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_set_header Cookie "";
        proxy_set_header X-Frappe-CSRF-Token "fetch";
        proxy_hide_header Set-Cookie;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
